[workspace.package]
edition = "2021"
name = "jskse"
rust-version = "1.71.1"
version = "1.0.0"
license = "ParityLicense-7.0"
authors = ["ItsSpyce"]
repository = "https://github.com/ItsSpyce/jskse"

[workspace]
resolver = "2"
members = ["crates/jskse_core"]
